### ISSUE TITLE
Stored files of music/skins

### ISSUE THREAD

**Issue by ghost** [Alexmitter/osu-lazer-linux-installer#8]
Question, where are stored music files/skin files in linux?
When I open "in-game" game directory it place me in `/home/whiteleash/.local/share/osu` but there are not too much to do with music/skins

**Comment by ghost** [comment]
I mean - I found Beatmap folder here > `/home/whiteleash/Desktop/osu-lazer-linux-installer/scripts/osu-stable/osu-resources/osu.Game.Resources/Beatmaps`
But when you use it and place there maps `.osz` and even restart game then nothing happened and no maps so guys (or girls) - where to place it?

**Comment by Alexmitter** [comment]
ignore the folders inside the build folder, osu creates and uses folders in the home directory.

The best way I found to import beatmaps is by making a .osu folder in your home directory and put the classic style beatmaps in it.
Currently the situation is bad because peppy somehow want beatmaps to no longer be portable or easily accessible as a folder. Why, idk.
About the skins. That I did not look for so far but I can take a look after the night.

**Comment by ghost** [comment]
Damn, it's the same situation in Windows version?

**Comment by Alexmitter** [comment]
Okay, let me explain it detailed now.
If you have an existing library from a windows installations, then make a .osu folder under home and put the Songs folder in it. osu!lazer will import them.

For the skins i currently have no solution, so there you may ask on osu!lazers github page.

Yes this strange beatmap situation will persists on the windows side too, why peppy does this is still not clear to me and he does not answer to my questions.

**Comment by ghost** [comment]
Ok I've got it :) 👍 Closing - if it will change if you can give feedback.

**Comment by toluschr** [comment]
@Alexmitter Its the same for skins. Just put the `Skin` directory into `$HOME/.osu` and import them.
